### ISSUE TITLE
Add instructions for building the ROM

### ISSUE THREAD

**Issue by ty-everett** [ANDROID2468/fire-os-revamped-7th-gen#2]
I'd be happy to help with this, but it would be helpful to know how this zip was put together. Is it just a modified copy of the original OEM zip?

**Comment by ANDROID2468** [comment]
> I'd be happy to help with this, but it would be helpful to know how this zip was put together. Is it just a modified copy of the original OEM zip?

What I do is I do all the modifications on the device its self, then I dump the system partition to a .img file with a dd command in TWRP recovery. Then I put that .img file into a update.zip with a boot.img file from amazon's update.zip. 
Here is a template for an update.zip  https://drive.google.com/file/d/1XM1JknWRVNAj65aI6V5xl8fbOhZzopAz/view

But right now I'm the only one that will do the packing up of this rom because I want to make sure the rom works before I release it and it will be harder for me to organize if I let more then one person do that for me. 

But that doesn't mean that you can't help me though.
If you come up with a good feature that you want in this rom and you want to mess around with doing this stuff, then you can flash my rom on your device and go crazy with it. Once you implement your feature, make an issue on my GitHub page of what the feature is and how you add it to the rom. I will mention you in my xda page under who contributed to this rom section (doesn't exist yet but it will be coming soon) if you come up with a good feature for this rom.
